[package]
name = "scouting-v3"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"

[workspace]
members = ["wasm", "server"]
